name: iOS CI

on:
  push:
    branches:
      - main
      - feature/ci-setup

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Create Secrets.xcconfig
        run: |
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > Secrets.xcconfig

      - name: Build NewsPulse
        run: |
          xcodebuild \
            -project NewsPulse.xcodeproj \
            -scheme NewsPulse \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project NewsPulse.xcodeproj \
            -scheme NewsPulse \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.5' \
            CODE_SIGNING_ALLOWED=NO \
            test
